import type { Metadata } from "next";
import { notFound } from "next/navigation";
import Link from "next/link";

/* ═══════════════════════════════════════════════════════════════════════════
   Language data — inline for programmatic SEO
   ═══════════════════════════════════════════════════════════════════════════ */

const LANGUAGES: Record<
  string,
  {
    name: string;
    ext: string;
    topVulns: string[];
    aiToolsUsed: string;
    detectPatterns: string[];
    description: string;
  }
> = {
  python: {
    name: "Python",
    ext: ".py",
    topVulns: [
      "SQL injection via f-strings",
      "pickle deserialization",
      "hardcoded secrets in Django settings",
      "MD5/SHA-1 hashing",
      "RSA with cryptography library",
    ],
    aiToolsUsed: "Copilot, Cursor, Claude",
    detectPatterns: [
      "f-string and %-format SQL query construction",
      "pickle.loads() on untrusted data",
      "hashlib.md5() and hashlib.sha1() usage",
      "Hardcoded SECRET_KEY in Django settings.py",
      "RSA key generation with cryptography and PyCryptodome",
      "ECDSA / Ed25519 signing (quantum-vulnerable)",
      "os.system() and subprocess with shell=True",
      "eval() / exec() on user-controlled input",
      "Flask debug mode in production",
      "Insecure PyYAML yaml.load() without SafeLoader",
    ],
    description:
      "Python is the most popular language for AI-assisted development, with over 70% of Copilot suggestions targeting Python files. This popularity means AI tools generate more Python code — and more Python vulnerabilities — than any other language. Common issues include SQL injection through f-string formatting, insecure deserialization via pickle, and widespread use of quantum-vulnerable cryptography like RSA and ECDSA through the cryptography library.",
  },
  javascript: {
    name: "JavaScript",
    ext: ".js/.ts",
    topVulns: [
      "eval() with user input",
      "innerHTML XSS",
      "SQL injection via template literals",
      "hardcoded API keys",
      "crypto.createHash('sha1')",
    ],
    aiToolsUsed: "Copilot, Cursor, v0",
    detectPatterns: [
      "Template literal SQL query construction",
      "innerHTML and outerHTML assignments with dynamic data",
      "document.write() with unsanitized input",
      "eval() and Function() constructor usage",
      "Hardcoded API keys, tokens, and secrets in source",
      "crypto.createHash('md5') and crypto.createHash('sha1')",
      "Node.js crypto RSA and ECDSA key generation",
      "CORS wildcard (*) configuration",
      "JWT secrets hardcoded in source files",
      "Disabled TLS certificate verification",
    ],
    description:
      "JavaScript is the backbone of web development and one of the most common targets for AI code generation tools. AI assistants frequently generate JavaScript with innerHTML assignments instead of textContent, build SQL queries with template literals instead of parameterized queries, and scatter API keys directly in source files. Node.js crypto module usage generated by AI almost always defaults to legacy algorithms like SHA-1 and MD5.",
  },
  typescript: {
    name: "TypeScript",
    ext: ".ts/.tsx",
    topVulns: [
      "dangerouslySetInnerHTML XSS",
      "SQL injection in Prisma raw queries",
      "JWT secrets in source",
      "CORS wildcard in Next.js",
      "weak crypto in Node.js",
    ],
    aiToolsUsed: "Copilot, Cursor, Claude",
    detectPatterns: [
      "dangerouslySetInnerHTML with unsanitized data",
      "Prisma $queryRaw and $executeRaw with interpolation",
      "TypeORM raw query string concatenation",
      "Hardcoded JWT_SECRET and API keys in .ts files",
      "Next.js API routes with CORS wildcard headers",
      "crypto.createHash with MD5/SHA-1",
      "RSA and ECDSA key generation via Node.js crypto",
      "Zod/Yup schema bypasses in form handling",
      "Server actions without proper input validation",
      "tRPC procedures missing authorization checks",
    ],
    description:
      "TypeScript projects — especially those using React, Next.js, and modern full-stack frameworks — are heavily targeted by AI code assistants. While TypeScript's type system catches some errors, it cannot prevent security vulnerabilities like XSS through dangerouslySetInnerHTML, SQL injection in Prisma raw queries, or hardcoded secrets. AI tools frequently generate Next.js API routes with overly permissive CORS and insecure JWT configurations.",
  },
  go: {
    name: "Go",
    ext: ".go",
    topVulns: [
      "SQL injection via fmt.Sprintf",
      "crypto/des usage",
      "hardcoded credentials",
      "TLS verification disabled",
      "crypto/rc4 usage",
    ],
    aiToolsUsed: "Copilot, Cursor",
    detectPatterns: [
      "fmt.Sprintf SQL query construction",
      "string concatenation in database queries",
      "crypto/des and crypto/rc4 package imports",
      "crypto/rsa key generation (quantum-vulnerable)",
      "crypto/ecdsa signing (quantum-vulnerable)",
      "Hardcoded passwords and API tokens in Go files",
      "TLS InsecureSkipVerify set to true",
      "net/http without timeouts (DoS risk)",
      "os/exec.Command with user-controlled arguments",
      "crypto/md5 and crypto/sha1 usage",
    ],
    description:
      "Go is the language of choice for cloud infrastructure, APIs, and microservices. AI code assistants generating Go code frequently use fmt.Sprintf to build SQL queries instead of parameterized statements, import deprecated crypto packages like crypto/des and crypto/rc4, and disable TLS verification for convenience. Go's standard library crypto/rsa and crypto/ecdsa are quantum-vulnerable and need migration to post-quantum alternatives before NIST's 2030 deadline.",
  },
  java: {
    name: "Java",
    ext: ".java",
    topVulns: [
      "SQL injection via string concat",
      "Cipher.getInstance DES",
      "MessageDigest MD5",
      "hardcoded passwords",
      "SSLv3 protocol",
    ],
    aiToolsUsed: "Copilot, Amazon Q",
    detectPatterns: [
      "String concatenation in PreparedStatement and Statement queries",
      "Cipher.getInstance(\"DES\") and Cipher.getInstance(\"DESede\")",
      "MessageDigest.getInstance(\"MD5\") and SHA-1",
      "KeyPairGenerator.getInstance(\"RSA\") — quantum-vulnerable",
      "KeyPairGenerator.getInstance(\"EC\") — quantum-vulnerable",
      "Hardcoded passwords, connection strings, and API keys",
      "SSLv3 and TLSv1.0 protocol usage",
      "Runtime.exec() with unsanitized input",
      "ObjectInputStream deserialization without filtering",
      "SecureRandom seeded with predictable values",
    ],
    description:
      "Java remains dominant in enterprise backends, financial systems, and Android development. AI assistants generate Java code that leans on legacy patterns: SQL queries built with string concatenation, DES and 3DES cipher usage via Cipher.getInstance, and MD5 digests via MessageDigest. Enterprise Java code is particularly vulnerable to quantum computing threats because RSA and ECDSA are deeply embedded in authentication, TLS, and digital signature workflows.",
  },
  rust: {
    name: "Rust",
    ext: ".rs",
    topVulns: [
      "SQL injection in raw queries",
      "hardcoded secrets",
      "weak RNG seeding",
      "RSA key generation",
      "SHA-1 hashing",
    ],
    aiToolsUsed: "Copilot, Cursor",
    detectPatterns: [
      "format!() macro used in SQL query construction",
      "sqlx::query() with string interpolation",
      "Hardcoded API keys and secrets in Rust source",
      "rsa crate RSA key generation (quantum-vulnerable)",
      "p256/p384 crate ECDSA usage (quantum-vulnerable)",
      "sha1 crate usage for security-critical hashing",
      "md-5 crate usage",
      "rand crate seeded with fixed values",
      "unsafe blocks with unchecked user input",
      "Disabled TLS verification in reqwest/hyper",
    ],
    description:
      "Rust's memory safety guarantees do not protect against logical security vulnerabilities. AI code assistants generating Rust frequently use format!() to build SQL queries, hardcode secrets directly in source files, and default to quantum-vulnerable cryptography. The rsa and p256 crates are widely suggested by AI tools but will need migration to post-quantum alternatives like ml-kem and ml-dsa crates.",
  },
  ruby: {
    name: "Ruby",
    ext: ".rb",
    topVulns: [
      "SQL injection via string interpolation",
      "eval() usage",
      "hardcoded API tokens",
      "OpenSSL legacy ciphers",
      "weak session secrets",
    ],
    aiToolsUsed: "Copilot, Cursor",
    detectPatterns: [
      "String interpolation in ActiveRecord where() clauses",
      "ActiveRecord find_by_sql with interpolated strings",
      "eval() and send() with user-controlled input",
      "Hardcoded API tokens in initializers and configs",
      "OpenSSL::Cipher::DES and legacy cipher usage",
      "OpenSSL::PKey::RSA key generation (quantum-vulnerable)",
      "OpenSSL::PKey::EC key generation (quantum-vulnerable)",
      "Digest::MD5 and Digest::SHA1 usage",
      "Weak secret_key_base in Rails credentials",
      "YAML.load() without safe_load",
    ],
    description:
      "Ruby on Rails applications are common targets for AI code generation, especially for CRUD operations and API endpoints. AI assistants frequently generate ActiveRecord queries using string interpolation instead of parameterized placeholders, include hardcoded API tokens in config/initializers, and use legacy OpenSSL ciphers. Rails' cryptographic foundations — including RSA for encrypted credentials — are quantum-vulnerable and need proactive migration planning.",
  },
  php: {
    name: "PHP",
    ext: ".php",
    topVulns: [
      "SQL injection via concatenation",
      "eval/exec injection",
      "hardcoded database passwords",
      "md5() for passwords",
      "weak session handling",
    ],
    aiToolsUsed: "Copilot, Cursor",
    detectPatterns: [
      "String concatenation in mysql_query and mysqli_query",
      "PDO queries without prepared statements",
      "eval(), exec(), system(), passthru() with user input",
      "Hardcoded database passwords in config files",
      "md5() and sha1() used for password hashing",
      "openssl_pkey_new with RSA type (quantum-vulnerable)",
      "openssl_sign with ECDSA (quantum-vulnerable)",
      "file_get_contents() with user-controlled URLs (SSRF)",
      "Insecure session.cookie_httponly configuration",
      "unserialize() on untrusted data",
    ],
    description:
      "PHP powers over 75% of websites and is frequently targeted by AI code generation for Laravel, WordPress, and API development. AI assistants commonly generate PHP code with SQL queries built via string concatenation instead of PDO prepared statements, use md5() for password hashing instead of password_hash(), and embed database credentials directly in configuration files. PHP's OpenSSL extension defaults to RSA, making quantum migration a critical concern for PHP applications.",
  },
};

/* ═══════════════════════════════════════════════════════════════════════════
   Static generation
   ═══════════════════════════════════════════════════════════════════════════ */

export function generateStaticParams() {
  return Object.keys(LANGUAGES).map((language) => ({ language }));
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ language: string }>;
}): Promise<Metadata> {
  const { language } = await params;
  const lang = LANGUAGES[language];
  if (!lang) return {};

  return {
    title: `AI Code Security Scanner for ${lang.name} | CodeShield.ai`,
    description: `Scan ${lang.name} (${lang.ext}) code generated by ${lang.aiToolsUsed} for SQL injection, XSS, hardcoded secrets, and quantum-vulnerable cryptography. Auto-fix with AI.`,
    keywords: [
      `${lang.name} code security scanner`,
      `${lang.name} AI code vulnerabilities`,
      `${lang.name} SQL injection scanner`,
      `${lang.name} secrets detection`,
      `${lang.name} post-quantum cryptography`,
      `AI generated ${lang.name} security`,
    ],
    alternates: { canonical: `/scan/${language}` },
    openGraph: {
      title: `AI Code Security Scanner for ${lang.name}`,
      description: `Detect and auto-fix vulnerabilities in AI-generated ${lang.name} code. ${lang.topVulns.length} common vulnerability patterns detected.`,
    },
  };
}

/* ═══════════════════════════════════════════════════════════════════════════
   Page component
   ═══════════════════════════════════════════════════════════════════════════ */

export default async function LanguageScanPage({
  params,
}: {
  params: Promise<{ language: string }>;
}) {
  const { language } = await params;
  const lang = LANGUAGES[language];

  if (!lang) {
    notFound();
  }

  return (
    <div className="min-h-screen bg-bg-primary">
      {/* ── Nav ── */}
      <nav className="flex items-center justify-between px-6 md:px-8 py-5 max-w-7xl mx-auto">
        <Link href="/" className="flex items-center gap-2">
          <div className="w-8 h-8 rounded-lg bg-green/20 flex items-center justify-center border border-green/30">
            <svg
              width="18"
              height="18"
              viewBox="0 0 24 24"
              fill="none"
              stroke="#00ff88"
              strokeWidth="2.5"
              strokeLinecap="round"
              strokeLinejoin="round"
            >
              <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z" />
            </svg>
          </div>
          <span className="font-bold text-lg tracking-tight text-text-primary">
            CodeShield<span className="text-green">.ai</span>
          </span>
        </Link>
        <div className="flex items-center gap-6">
          <Link
            href="/"
            className="text-sm text-text-secondary hover:text-text-primary transition-colors"
          >
            Home
          </Link>
          <Link
            href="/pricing"
            className="text-sm text-text-secondary hover:text-text-primary transition-colors hidden sm:block"
          >
            Pricing
          </Link>
        </div>
      </nav>

      <div className="max-w-4xl mx-auto px-6 md:px-8 py-12 md:py-20">
        {/* ── Header ── */}
        <div className="mb-12">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full border border-green/30 bg-green/10 mb-6">
            <span className="text-xs font-medium text-green font-mono">
              {lang.ext} files
            </span>
          </div>
          <h1 className="text-3xl sm:text-4xl md:text-5xl font-bold text-text-primary mb-6 leading-tight">
            AI Code Security Scanner for{" "}
            <span className="text-green">{lang.name}</span>
          </h1>
          <p className="text-text-secondary text-lg leading-relaxed max-w-3xl">
            {lang.description}
          </p>
        </div>

        {/* ── Top vulnerabilities ── */}
        <section className="mb-14">
          <h2 className="text-xl md:text-2xl font-bold text-text-primary mb-6">
            Top vulnerabilities AI tools generate in {lang.name} code
          </h2>
          <div className="grid gap-3">
            {lang.topVulns.map((vuln, i) => (
              <div
                key={i}
                className="flex items-start gap-3 bg-bg-card border border-border rounded-xl p-4 hover:border-border-light transition-colors"
              >
                <div className="w-8 h-8 rounded-lg bg-red/10 flex items-center justify-center shrink-0 mt-0.5">
                  <span className="text-sm font-bold font-mono text-red">
                    {i + 1}
                  </span>
                </div>
                <div>
                  <p className="text-text-primary font-medium">{vuln}</p>
                  <p className="text-xs text-text-secondary mt-1">
                    Frequently generated by AI assistants writing {lang.name}{" "}
                    code
                  </p>
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* ── What CodeShield detects ── */}
        <section className="mb-14">
          <h2 className="text-xl md:text-2xl font-bold text-text-primary mb-6">
            What CodeShield detects in {lang.name} files
          </h2>
          <div className="bg-bg-card border border-border rounded-2xl p-6 md:p-8">
            <p className="text-text-secondary mb-6 leading-relaxed">
              CodeShield performs deep static analysis on {lang.ext} files to
              detect OWASP Top 10 vulnerabilities, exposed secrets,
              quantum-vulnerable cryptography, and insecure coding patterns
              specific to the {lang.name} ecosystem.
            </p>
            <div className="grid sm:grid-cols-2 gap-3">
              {lang.detectPatterns.map((pattern, i) => (
                <div key={i} className="flex items-start gap-2">
                  <svg
                    className="w-4 h-4 text-green shrink-0 mt-1"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="2.5"
                  >
                    <polyline points="20 6 9 17 4 12" />
                  </svg>
                  <span className="text-sm text-text-secondary">{pattern}</span>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* ── AI tools ── */}
        <section className="mb-14">
          <h2 className="text-xl md:text-2xl font-bold text-text-primary mb-6">
            AI tools that generate {lang.name} code
          </h2>
          <div className="bg-bg-card border border-border rounded-2xl p-6 md:p-8">
            <p className="text-text-secondary leading-relaxed mb-4">
              The following AI coding assistants actively generate {lang.name}{" "}
              code and are known to introduce the vulnerability patterns listed
              above:
            </p>
            <div className="flex flex-wrap gap-3">
              {lang.aiToolsUsed.split(", ").map((tool) => (
                <span
                  key={tool}
                  className="inline-flex items-center gap-2 px-4 py-2 rounded-lg bg-bg-primary border border-border text-text-primary text-sm font-medium"
                >
                  <span className="w-2 h-2 rounded-full bg-orange" />
                  {tool}
                </span>
              ))}
            </div>
            <p className="text-text-dim text-xs mt-4">
              These tools produce correct code in most cases, but studies show
              that up to 45% of AI-generated code contains at least one security
              vulnerability. CodeShield catches what code review misses.
            </p>
          </div>
        </section>

        {/* ── CTA ── */}
        <section className="text-center">
          <div className="bg-bg-card border border-border rounded-2xl p-8 md:p-12 relative overflow-hidden">
            <div className="absolute inset-0 bg-gradient-to-br from-green/5 via-transparent to-orange/5 pointer-events-none" />
            <div className="relative">
              <h2 className="text-2xl md:text-3xl font-bold text-text-primary mb-4">
                Scan your {lang.name} repos free
              </h2>
              <p className="text-text-secondary mb-8 max-w-lg mx-auto">
                Connect your GitHub account, select your {lang.name}{" "}
                repositories, and get a full security report in under two
                minutes. No credit card required.
              </p>
              <Link
                href="/dashboard"
                className="inline-flex items-center gap-3 px-8 py-4 bg-green text-bg-primary font-semibold text-lg rounded-xl hover:bg-green-dim transition-all glow-green"
              >
                <svg
                  width="20"
                  height="20"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="2.5"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                >
                  <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z" />
                </svg>
                Scan Your {lang.name} Repos Free
              </Link>
            </div>
          </div>
        </section>
      </div>

      {/* ── Footer ── */}
      <footer className="border-t border-border py-8 px-6 md:px-8 mt-12">
        <div className="max-w-7xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-2">
            <div className="w-6 h-6 rounded bg-green/20 flex items-center justify-center border border-green/30">
              <svg
                width="12"
                height="12"
                viewBox="0 0 24 24"
                fill="none"
                stroke="#00ff88"
                strokeWidth="3"
                strokeLinecap="round"
                strokeLinejoin="round"
              >
                <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z" />
              </svg>
            </div>
            <span className="text-sm text-text-dim">
              CodeShield.ai &copy; {new Date().getFullYear()}
            </span>
          </div>
          <div className="flex items-center gap-6 text-sm text-text-dim">
            <Link
              href="/pricing"
              className="hover:text-text-secondary transition-colors"
            >
              Pricing
            </Link>
            <a
              href="mailto:hello@codeshield.ai"
              className="hover:text-text-secondary transition-colors"
            >
              Contact
            </a>
          </div>
        </div>
      </footer>
    </div>
  );
}
